/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentMan;

import MainObjects.ExtraCurricularEntity;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class ExtraCurricularChooser extends javax.swing.JDialog {

    private ExtraCurricularEntity entity;
    private int ID_Extra;

    /**
     * Creates new form StaffChooser
     */
    public ExtraCurricularChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.entity  = new ExtraCurricularEntity();
        initComponents();
        initUI();
    }
    private void initUI() {
        btnChoose.setEnabled(false);
        entity.loadList(tblExtra);
        
    }

    public int getChooser() {
        return ID_Extra;
    }

    private void search() {
        String name=txtNameSearch.getText();
        int monthStart = 0;
        int monthEnd = 0;
        int yearStart = 0;
        int yearEnd = 0;
        try {
            if (comboMonthStartSearch.getSelectedIndex() != 0) {
                monthStart=Integer.parseInt(comboMonthStartSearch.getSelectedItem().toString());
            }
            if (comboMonthEndSearch.getSelectedIndex() != 0) {
                monthEnd=Integer.parseInt(comboMonthStartSearch.getSelectedItem().toString());
            }
            if(!txtYearStartSearch.getText().isEmpty()){
                yearStart=Integer.parseInt(txtYearStartSearch.getText());
            }
            if(!txtYearEndSearch.getText().isEmpty()){
                yearEnd=Integer.parseInt(txtYearStartSearch.getText());
            }
            
        } catch (NullPointerException | NumberFormatException ex) {}
        entity.search(name, monthStart, yearStart, monthEnd, yearEnd, tblExtra);
        btnChoose.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bannerPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNameSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboMonthStartSearch = new javax.swing.JComboBox();
        txtYearStartSearch = new javax.swing.JTextField();
        comboMonthEndSearch = new javax.swing.JComboBox();
        txtYearEndSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNameSearch1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExtra = new javax.swing.JTable();
        btnChoose = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 129, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bannerPanel.setBackground(new java.awt.Color(45, 129, 171));
        bannerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 51, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        bannerPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 30, 20));

        txtNameSearch.setBackground(new java.awt.Color(85, 153, 187));
        txtNameSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtNameSearch.setBorder(null);
        txtNameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameSearchsearchAction(evt);
            }
        });
        bannerPanel.add(txtNameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 170, 26));

        jLabel4.setBackground(new java.awt.Color(0, 102, 153));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Curriculum_40px.png"))); // NOI18N
        jLabel4.setText("Extra Curricular Chooser");
        jLabel4.setIconTextGap(14);
        jLabel4.setOpaque(true);
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        bannerPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        comboMonthStartSearch.setBackground(new java.awt.Color(85, 153, 187));
        comboMonthStartSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboMonthStartSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboMonthStartSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 71, 104)));
        comboMonthStartSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonthStartSearchActionPerformed(evt);
            }
        });
        bannerPanel.add(comboMonthStartSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 127, 26));

        txtYearStartSearch.setBackground(new java.awt.Color(85, 153, 187));
        txtYearStartSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtYearStartSearch.setBorder(null);
        txtYearStartSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearStartSearchActionPerformed(evt);
            }
        });
        bannerPanel.add(txtYearStartSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 70, 26));

        comboMonthEndSearch.setBackground(new java.awt.Color(85, 153, 187));
        comboMonthEndSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboMonthEndSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboMonthEndSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 71, 104)));
        comboMonthEndSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonthEndSearchActionPerformed(evt);
            }
        });
        bannerPanel.add(comboMonthEndSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 127, 26));

        txtYearEndSearch.setBackground(new java.awt.Color(85, 153, 187));
        txtYearEndSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtYearEndSearch.setBorder(null);
        bannerPanel.add(txtYearEndSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, 26));

        jLabel5.setBackground(new java.awt.Color(0, 102, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Start Date");
        jLabel5.setOpaque(true);
        bannerPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, 26));

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("End Date");
        jLabel6.setOpaque(true);
        bannerPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 26));

        jLabel7.setBackground(new java.awt.Color(0, 102, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Title");
        jLabel7.setOpaque(true);
        bannerPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 90, 26));

        jLabel8.setBackground(new java.awt.Color(255, 102, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_15px.png"))); // NOI18N
        jLabel8.setText("Search");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        bannerPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 90, 26));

        jLabel10.setBackground(new java.awt.Color(0, 102, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Reset_18px_1.png"))); // NOI18N
        jLabel10.setText("Reset");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        bannerPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 90, 26));

        txtNameSearch1.setBackground(new java.awt.Color(85, 153, 187));
        txtNameSearch1.setForeground(new java.awt.Color(255, 255, 255));
        txtNameSearch1.setBorder(null);
        txtNameSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameSearch1searchAction(evt);
            }
        });
        bannerPanel.add(txtNameSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 170, 26));

        jLabel12.setBackground(new java.awt.Color(0, 102, 153));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ID");
        jLabel12.setOpaque(true);
        bannerPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 90, 26));

        jPanel1.add(bannerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 180));

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 153));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 1, true));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        tblExtra.setBackground(new java.awt.Color(4, 74, 121));
        tblExtra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblExtra.setForeground(new java.awt.Color(255, 255, 255));
        tblExtra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Location", "Start", "End"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExtra.setGridColor(new java.awt.Color(0, 102, 153));
        tblExtra.setSelectionBackground(new java.awt.Color(0, 204, 51));
        tblExtra.setShowHorizontalLines(false);
        tblExtra.setShowVerticalLines(false);
        tblExtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExtraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblExtra);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 689, 264));

        btnChoose.setBackground(new java.awt.Color(51, 204, 0));
        btnChoose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChoose.setForeground(new java.awt.Color(255, 255, 255));
        btnChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Ok_15px.png"))); // NOI18N
        btnChoose.setText("Choose");
        btnChoose.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Checked_18px.png"))); // NOI18N
        btnChoose.setOpaque(true);
        btnChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseMouseClicked(evt);
            }
        });
        jPanel1.add(btnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 90, 26));

        jLabel11.setBackground(new java.awt.Color(255, 51, 51));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        jLabel11.setText("Cancel");
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 90, 26));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblExtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExtraMouseClicked
        btnChoose.setEnabled(true);
    }//GEN-LAST:event_tblExtraMouseClicked

    private void txtNameSearchsearchAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameSearchsearchAction
        search();
    }//GEN-LAST:event_txtNameSearchsearchAction

    private void comboMonthStartSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonthStartSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMonthStartSearchActionPerformed

    private void comboMonthEndSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonthEndSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMonthEndSearchActionPerformed

    private void txtYearStartSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearStartSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearStartSearchActionPerformed

    private void btnChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseMouseClicked
 ID_Extra = entity.getSelectID(tblExtra);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    search();     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
ID_Extra = -1;
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked
int xMouse;
int yMouse;
    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
 xMouse=evt.getX();
        yMouse=evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
     int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseDragged

    private void txtNameSearch1searchAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameSearch1searchAction
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameSearch1searchAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtraCurricularChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtraCurricularChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtraCurricularChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtraCurricularChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExtraCurricularChooser dialog = new ExtraCurricularChooser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JLabel btnChoose;
    private javax.swing.JComboBox comboMonthEndSearch;
    private javax.swing.JComboBox comboMonthStartSearch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExtra;
    private javax.swing.JTextField txtNameSearch;
    private javax.swing.JTextField txtNameSearch1;
    private javax.swing.JTextField txtYearEndSearch;
    private javax.swing.JTextField txtYearStartSearch;
    // End of variables declaration//GEN-END:variables
}
