/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentMan;

import Controls.StudentManager;
import MainObjects.ExtraCurricularEntity;
import java.util.Vector;
import javax.swing.JOptionPane;
import TableModel.ExtraCurricular;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class ExtraCurricularUpdate extends javax.swing.JDialog {
    private ExtraCurricular curricular;
    private ExtraCurricularEntity entity;
    /**
     * Creates new form StudentMoreInfoDialog
     */
    public ExtraCurricularUpdate(java.awt.Frame parent, boolean modal, Vector data) {
        super(parent, modal);
        
        this.entity=new ExtraCurricularEntity();
        if(data!=null){
            this.curricular=new ExtraCurricular();
            curricular.setName(data.get(1).toString());
            curricular.setLocation(data.get(2).toString());
            curricular.setStart(entity.parseDate(data.get(3).toString()));
            curricular.setEnd(entity.parseDate(data.get(4).toString()));
            curricular.setNotes(data.get(5).toString());
        }
        initComponents();
        setLocationRelativeTo(this);
        initUI();
    }
    private void initUI(){
        if(curricular==null){
            return;
        }
        labelName.setText(curricular.getName());
        labelLocation.setText(curricular.getLocation());
        labelStart.setText(entity.formatDate(curricular.getStart()));
        labelEnd.setText(entity.formatDate(curricular.getEnd()));
        txtNotes.setText(curricular.getNotes());
        
    }
    private void chooser(){
        if(curricular==null){
            curricular=new ExtraCurricular();
        }
        ExtraCurricularChooser chooser=new ExtraCurricularChooser(null, true);
        chooser.setVisible(true);
        if(chooser.getChooser() >0){
            curricular=entity.findByID(chooser.getChooser());   
        }
        initUI();
    }
    private void save(){
        if(curricular==null){
            curricular=new ExtraCurricular();
        }
        if(curricular.getID()<=0){
            JOptionPane.showMessageDialog(this, "You must choose Extra Curricular !");
            return;
        }
        
        curricular.setNotes(txtNotes.getText());
        dispose();
        
    }

    public ExtraCurricular getExtraCurricular() {
        return curricular;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        labelName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelStart = new javax.swing.JTextField();
        labelEnd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(85, 153, 187));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 102, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Notes");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 90, 90));

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Browse_Folder_18px.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 40, 26));

        jScrollPane2.setBorder(null);

        txtNotes.setEditable(false);
        txtNotes.setBackground(new java.awt.Color(45, 129, 171));
        txtNotes.setColumns(20);
        txtNotes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNotes.setRows(5);
        txtNotes.setBorder(null);
        jScrollPane2.setViewportView(txtNotes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 270, 90));

        labelName.setBackground(new java.awt.Color(45, 129, 171));
        labelName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Name");
        labelName.setOpaque(true);
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 230, 26));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        jLabel2.setText("Cancel");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 80, 26));

        labelLocation.setBackground(new java.awt.Color(45, 129, 171));
        labelLocation.setForeground(java.awt.Color.white);
        labelLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelLocation.setBorder(null);
        labelLocation.setEnabled(false);
        jPanel1.add(labelLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 270, 26));

        jLabel3.setBackground(new java.awt.Color(0, 102, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Location");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, 26));

        jLabel6.setBackground(new java.awt.Color(51, 204, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_18px.png"))); // NOI18N
        jLabel6.setText("Save");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 90, 26));

        labelStart.setBackground(new java.awt.Color(45, 129, 171));
        labelStart.setForeground(java.awt.Color.white);
        labelStart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelStart.setBorder(null);
        labelStart.setEnabled(false);
        jPanel1.add(labelStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 270, 26));

        labelEnd.setBackground(new java.awt.Color(45, 129, 171));
        labelEnd.setForeground(java.awt.Color.white);
        labelEnd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelEnd.setBorder(null);
        labelEnd.setEnabled(false);
        jPanel1.add(labelEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 270, 26));

        jLabel11.setBackground(new java.awt.Color(0, 102, 153));
        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Curriculum_40px.png"))); // NOI18N
        jLabel11.setText("Extra Curricular Update");
        jLabel11.setIconTextGap(14);
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -8, 510, 60));

        jLabel7.setBackground(new java.awt.Color(0, 102, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("End");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, 26));

        jLabel5.setBackground(new java.awt.Color(0, 102, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Start");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 90, 26));

        jLabel8.setBackground(new java.awt.Color(0, 102, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Reset_18px_1.png"))); // NOI18N
        jLabel8.setText("Reset");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 80, 26));

        jLabel9.setBackground(new java.awt.Color(0, 102, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Name");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, 26));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        curricular=null;
    }//GEN-LAST:event_formWindowClosing

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      chooser();    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      curricular=null;
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        initUI();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       save();   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField labelEnd;
    private javax.swing.JTextField labelLocation;
    private javax.swing.JLabel labelName;
    private javax.swing.JTextField labelStart;
    private javax.swing.JTextArea txtNotes;
    // End of variables declaration//GEN-END:variables
}
