/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentMan;

import Controls.StudentManager;
import MainObjects.StaffEntity;
import java.util.Vector;
import javax.swing.JOptionPane;
import TableModel.Remark;
import TableModel.Staff;
import Employee.StaffChooser;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class RemarkUpdate extends javax.swing.JDialog {
    private Remark remark;
    private StaffEntity staffEntity;
    /**
     * Creates new form StudentMoreInfoDialog
     */
    public RemarkUpdate(java.awt.Frame parent, boolean modal, Vector data, StudentManager studentManager) {
        super(parent, modal);
        this.staffEntity=new StaffEntity();
        if(data!=null){
            this.remark=new Remark(Integer.parseInt(data.get(0).toString()), data.get(3).toString(), studentManager.parseDate(data.get(4).toString()), new Staff(Integer.parseInt(data.get(1).toString()), data.get(2).toString()));
        }
        initComponents();
        setLocationRelativeTo(this);
        initUI();
    }
    private void initUI(){
        if(remark==null){
            return;
        }
        labelStaffNo.setText(remark.getStaff().getNo()+"");
        labelStaffName.setText(remark.getStaff().getName());
        txtContent.setText(remark.getContent());
        dPic.setDate(remark.getTime());
    }
    private void staffChooser(){
        if(remark==null){
            remark=new Remark();
        }
        StaffChooser chooser=new StaffChooser(null, true);
        chooser.setVisible(true);
        if(chooser.getChooser() >0){
            remark.setStaff(staffEntity.findByID(chooser.getChooser()));
            labelStaffNo.setText(remark.getStaff().getNo()+"");
            labelStaffName.setText(remark.getStaff().getName());
        }
    }
    private void save(){
        if(remark==null){
            remark=new Remark();
        }
        if(remark.getStaff().getNo()<=0){
            JOptionPane.showMessageDialog(this, "You must choose Staff !");
            return;
        }
        
        remark.setContent(txtContent.getText());
        remark.setTime(dPic.getDate());
        dispose();
        
    }

    public Remark getRemark() {
        return remark;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        labelStaffNo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelStaffName = new javax.swing.JLabel();
        dPic = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(45, 129, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(1, 100, 151));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Content");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 90, 75));

        jLabel5.setBackground(new java.awt.Color(51, 204, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Browse_Folder_18px.png"))); // NOI18N
        jLabel5.setText("Select");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 70, 24));

        jLabel1.setBackground(new java.awt.Color(1, 100, 151));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Staff No");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 24));

        jScrollPane2.setBackground(new java.awt.Color(85, 153, 187));
        jScrollPane2.setBorder(null);

        txtContent.setBackground(new java.awt.Color(85, 153, 187));
        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContent.setForeground(new java.awt.Color(255, 255, 255));
        txtContent.setRows(5);
        txtContent.setBorder(null);
        jScrollPane2.setViewportView(txtContent);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 320, -1));

        labelStaffNo.setBackground(new java.awt.Color(85, 153, 187));
        labelStaffNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelStaffNo.setForeground(new java.awt.Color(255, 255, 255));
        labelStaffNo.setText("Staff No ");
        labelStaffNo.setOpaque(true);
        jPanel1.add(labelStaffNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 250, 24));

        jLabel2.setBackground(new java.awt.Color(1, 100, 151));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Staff Name");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 24));

        labelStaffName.setBackground(new java.awt.Color(85, 153, 187));
        labelStaffName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelStaffName.setForeground(new java.awt.Color(255, 255, 255));
        labelStaffName.setText("Staff Name");
        labelStaffName.setOpaque(true);
        jPanel1.add(labelStaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 320, 24));

        dPic.setBackground(new java.awt.Color(85, 153, 187));
        jPanel1.add(dPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 320, 24));

        jLabel11.setBackground(new java.awt.Color(0, 102, 153));
        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Note_24px_2.png"))); // NOI18N
        jLabel11.setText("Remark Update");
        jLabel11.setIconTextGap(14);
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 55));

        jLabel6.setBackground(new java.awt.Color(204, 0, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        jLabel6.setText("Cancel");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 90, 24));

        jLabel7.setBackground(new java.awt.Color(1, 100, 151));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Time");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, 24));

        jLabel8.setBackground(new java.awt.Color(51, 204, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_18px.png"))); // NOI18N
        jLabel8.setText("Save");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 90, 24));

        jLabel9.setBackground(new java.awt.Color(0, 153, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Reset_18px_1.png"))); // NOI18N
        jLabel9.setText("Reset");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 90, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        remark=null;
    }//GEN-LAST:event_formWindowClosing

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
staffChooser();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
 save();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
initUI();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
remark=null;
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dPic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelStaffName;
    private javax.swing.JLabel labelStaffNo;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables
}
