/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentMan;

import MainObjects.BatchEntity;
import MainObjects.StudentEntity;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class StudentChooser extends javax.swing.JDialog {

    private StudentEntity studentEntity;
    private BatchEntity batchEntity;
    private int ID_Student; 

    int xMouse;
    int yMouse;/**
     * Creates new form StaffChooser
     */
    public StudentChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        studentEntity = new StudentEntity();
        batchEntity = new BatchEntity();
        initComponents();
        initUI();
    }
    private void initUI() {
        btnChoose.setEnabled(false);
        loadBatch();
        studentEntity.loadList(tblStudent);
        loadBatch();
    }

    public int getChooser() {
        return ID_Student;
    }
    
    private void loadBatch(){
        comboBatch.removeAllItems();
        comboBatch.addItem("Choose");
        for(String s:batchEntity.getNameList()){
            comboBatch.addItem(s);
        }
    }

    private void search() {
        String No = txtNo.getText();
        String name=txtName.getText();
        int registerNo=0;
        int batch = 0;
        try {
            if (comboBatch.getSelectedIndex() != 0) {
                batch = batchEntity.findByName(comboBatch.getSelectedItem().toString()).getID();
            }
        } catch (NullPointerException ex) {
            ex.printStackTrace();
                    }
        if (!txtRegisterNo.getText().isEmpty()) {
            try {
                registerNo = Integer.parseInt(txtRegisterNo.getText());
            } catch (NumberFormatException ex) {
            }
        }
        studentEntity.search(registerNo, No, txtName.getText(), batch,tblStudent);
        btnChoose.setEnabled(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFH = new javax.swing.JPanel();
        cnclBut = new javax.swing.JLabel();
        txtRegisterNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        comboBatch = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        btnChoose = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(178, 208, 224));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainFH.setBackground(new java.awt.Color(45, 129, 171));
        mainFH.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainFH.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        mainFH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainFHMouseDragged(evt);
            }
        });
        mainFH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainFHMousePressed(evt);
            }
        });
        mainFH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainFHKeyPressed(evt);
            }
        });
        mainFH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cnclBut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cnclBut.setForeground(new java.awt.Color(255, 255, 255));
        cnclBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px.png"))); // NOI18N
        cnclBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnclButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnclButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cnclButMouseExited(evt);
            }
        });
        mainFH.add(cnclBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 21, 20));

        txtRegisterNo.setBackground(new java.awt.Color(85, 153, 187));
        txtRegisterNo.setBorder(null);
        txtRegisterNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterNoActionPerformed(evt);
            }
        });
        mainFH.add(txtRegisterNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 26));

        jScrollPane1.setBackground(new java.awt.Color(4, 74, 121));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 74, 121)));

        tblStudent.setBackground(new java.awt.Color(0, 51, 102));
        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Register No", "No", "Name", "Batch", "Phone", "Email", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudent);

        mainFH.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 220, 710, 274));

        comboBatch.setBackground(new java.awt.Color(85, 153, 187));
        comboBatch.setEditable(true);
        comboBatch.setBorder(null);
        mainFH.add(comboBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 150, 26));

        jLabel5.setBackground(new java.awt.Color(1, 100, 151));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Batch");
        jLabel5.setOpaque(true);
        mainFH.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, 26));

        jLabel4.setBackground(new java.awt.Color(1, 100, 151));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Register No");
        jLabel4.setOpaque(true);
        mainFH.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 26));

        jLabel3.setBackground(new java.awt.Color(0, 102, 153));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Student_Male_38px.png"))); // NOI18N
        jLabel3.setText("Student Chooser");
        jLabel3.setIconTextGap(12);
        jLabel3.setOpaque(true);
        mainFH.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 786, 60));

        txtName.setBackground(new java.awt.Color(85, 153, 187));
        txtName.setBorder(null);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        mainFH.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 150, 26));

        jLabel2.setBackground(new java.awt.Color(1, 100, 151));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        jLabel2.setOpaque(true);
        mainFH.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 110, 26));

        txtNo.setBackground(new java.awt.Color(85, 153, 187));
        txtNo.setBorder(null);
        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        mainFH.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, 26));

        jLabel1.setBackground(new java.awt.Color(1, 100, 151));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Roll No");
        jLabel1.setOpaque(true);
        mainFH.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 26));

        btnSearch.setBackground(new java.awt.Color(255, 102, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_18px_2.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setOpaque(true);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        mainFH.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 90, 26));

        btnChoose.setBackground(new java.awt.Color(51, 204, 0));
        btnChoose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChoose.setForeground(new java.awt.Color(255, 255, 255));
        btnChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Checked_18px.png"))); // NOI18N
        btnChoose.setText("Choose");
        btnChoose.setOpaque(true);
        btnChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseMouseClicked(evt);
            }
        });
        mainFH.add(btnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 90, 26));

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        mainFH.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 90, 26));

        getContentPane().add(mainFH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
btnChoose.setEnabled(true);

    }//GEN-LAST:event_tblStudentMouseClicked

    private void txtRegisterNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterNoActionPerformed

    private void cnclButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnclButMouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cnclButMouseClicked

    private void cnclButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnclButMouseEntered
        cnclBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_1.png")));   // TODO add your handling code here:
    }//GEN-LAST:event_cnclButMouseEntered

    private void cnclButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnclButMouseExited
        cnclBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px.png")));    // TODO add your handling code here:
    }//GEN-LAST:event_cnclButMouseExited

    private void mainFHMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFHMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);// TODO add your handling code here:
    }//GEN-LAST:event_mainFHMouseDragged

    private void mainFHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFHMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_mainFHMousePressed

    private void mainFHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainFHKeyPressed

    }//GEN-LAST:event_mainFHKeyPressed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
      search();  // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
       ID_Student = -1;
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseMouseClicked
    ID_Student = studentEntity.getSelectID(tblStudent);
        dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentChooser dialog = new StudentChooser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnChoose;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel cnclBut;
    private javax.swing.JComboBox comboBatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainFH;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtRegisterNo;
    // End of variables declaration//GEN-END:variables
}
