/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import Controls.GeneralManager;
import TableModel.Feedback;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class FeedbackDetail extends javax.swing.JDialog {
    private Feedback feedback;
    private GeneralManager manager;
    /**
     * Creates new form StudentMoreInfoDialog
     */
    public FeedbackDetail(java.awt.Frame parent, boolean modal, Feedback feedback) {
        super(parent, modal);
        this.feedback=feedback;
        this.manager=new GeneralManager();
        initComponents();
        setLocationRelativeTo(this);
        initUI();
    }
    private void initUI(){
        labelID.setText(feedback.getID()+"");
        labelStudentRegisterNo.setText(feedback.getStudent().getRegisterNo()+"");
        labelStudentName.setText(feedback.getStudent().getName());
        txtContent.setText(feedback.getContent());
        labelTime.setText(manager.formatDate(feedback.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Content = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelStudentRegisterNo = new javax.swing.JLabel();
        labelStudentName = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 129, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 152));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, 25));

        jLabel2.setBackground(new java.awt.Color(0, 102, 152));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student register No");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, 25));

        jLabel3.setBackground(new java.awt.Color(0, 102, 152));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Student name");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, 25));

        Content.setBackground(new java.awt.Color(0, 102, 152));
        Content.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Content.setForeground(new java.awt.Color(255, 255, 255));
        Content.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Content.setText("Content");
        Content.setOpaque(true);
        jPanel1.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 80));

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_Window_17px.png"))); // NOI18N
        jLabel5.setText("CLOSE");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 70, 25));

        labelID.setBackground(new java.awt.Color(85, 153, 187));
        labelID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelID.setForeground(new java.awt.Color(255, 255, 255));
        labelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID.setText("ID");
        labelID.setOpaque(true);
        jPanel1.add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 320, 25));

        labelStudentRegisterNo.setBackground(new java.awt.Color(85, 153, 187));
        labelStudentRegisterNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStudentRegisterNo.setForeground(new java.awt.Color(255, 255, 255));
        labelStudentRegisterNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStudentRegisterNo.setText("Student register No");
        labelStudentRegisterNo.setOpaque(true);
        jPanel1.add(labelStudentRegisterNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 320, 25));

        labelStudentName.setBackground(new java.awt.Color(85, 153, 187));
        labelStudentName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStudentName.setForeground(new java.awt.Color(255, 255, 255));
        labelStudentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStudentName.setText("Student name");
        labelStudentName.setOpaque(true);
        jPanel1.add(labelStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 320, 25));

        labelTime.setBackground(new java.awt.Color(85, 153, 187));
        labelTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTime.setForeground(new java.awt.Color(255, 255, 255));
        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTime.setText("Time");
        labelTime.setOpaque(true);
        jPanel1.add(labelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 320, 25));

        jScrollPane1.setBorder(null);

        txtContent.setBackground(new java.awt.Color(85, 153, 187));
        txtContent.setBorder(null);
        txtContent.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtContent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 320, 80));

        jLabel11.setBackground(new java.awt.Color(0, 102, 153));
        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Feedback Detail");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 550, 60));

        jLabel6.setBackground(new java.awt.Color(0, 102, 152));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Time");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, 25));

        jLabel7.setBackground(new java.awt.Color(51, 204, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Checked_18px.png"))); // NOI18N
        jLabel7.setText("OK");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 70, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelStudentName;
    private javax.swing.JLabel labelStudentRegisterNo;
    private javax.swing.JLabel labelTime;
    private javax.swing.JTextPane txtContent;
    // End of variables declaration//GEN-END:variables
}
