/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import Controls.GeneralManager;
import Controls.StaffManager;
import TableModel.Promotion;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class PromotionDetail extends javax.swing.JDialog {
    private Promotion promotion;
    private GeneralManager manager;
    /**
     * Creates new form StudentMoreInfoDialog
     */
    public PromotionDetail(java.awt.Frame parent, boolean modal, Promotion promotion) {
        super(parent, modal);
        this.manager=new GeneralManager();
        this.promotion=promotion;
        initComponents();
        setLocationRelativeTo(this);
        initUI();
    }
    private void initUI(){
        labelID.setText(promotion.getID()+"");
        labelPositionName.setText(promotion.getPosition().getName());
        labelDepartmentName.setText(promotion.getPosition().getDepartment().getName());
        labelDate.setText(manager.formatDate(promotion.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelPositionName = new javax.swing.JLabel();
        labelDepartmentName = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 129, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(1, 100, 151));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 25));

        jLabel2.setBackground(new java.awt.Color(1, 100, 151));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Position name");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 25));

        jLabel4.setBackground(new java.awt.Color(1, 100, 151));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Department name");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 25));

        jLabel5.setBackground(new java.awt.Color(1, 100, 151));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Date");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 25));

        labelID.setBackground(new java.awt.Color(85, 153, 187));
        labelID.setForeground(new java.awt.Color(255, 255, 255));
        labelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID.setText("ID");
        labelID.setOpaque(true);
        jPanel1.add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 270, 25));

        labelPositionName.setBackground(new java.awt.Color(85, 153, 187));
        labelPositionName.setForeground(new java.awt.Color(255, 255, 255));
        labelPositionName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPositionName.setText("Position name");
        labelPositionName.setOpaque(true);
        jPanel1.add(labelPositionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, 25));

        labelDepartmentName.setBackground(new java.awt.Color(85, 153, 187));
        labelDepartmentName.setForeground(new java.awt.Color(255, 255, 255));
        labelDepartmentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDepartmentName.setText("Department name");
        labelDepartmentName.setOpaque(true);
        jPanel1.add(labelDepartmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 270, 25));

        labelDate.setBackground(new java.awt.Color(85, 153, 187));
        labelDate.setForeground(new java.awt.Color(255, 255, 255));
        labelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDate.setText("Date");
        labelDate.setOpaque(true);
        jPanel1.add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 270, 25));

        jLabel11.setBackground(new java.awt.Color(0, 102, 153));
        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Buy_Upgrade_30px_1.png"))); // NOI18N
        jLabel11.setText("Poromotion Detail");
        jLabel11.setIconTextGap(16);
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 480, 50));

        jLabel6.setBackground(new java.awt.Color(51, 204, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Ok_18px.png"))); // NOI18N
        jLabel6.setText("Ok");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 88, 25));

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        jLabel7.setText("Close");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 88, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
     dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
     dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDepartmentName;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelPositionName;
    // End of variables declaration//GEN-END:variables
}
