/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import Controls.GeneralManager;
import java.awt.Frame;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import TableModel.Department;
import TableModel.Position;
import TableModel.Promotion;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class PromotionUpdate extends javax.swing.JDialog {

    private Promotion promotion;
    private Promotion newPromotion;
    private GeneralManager manager;

    /**
     * Creates new form StudentMoreInfoDialog
     */
    public PromotionUpdate(Frame parent, boolean modal,  Vector data) {
        super(parent, modal);
        this.manager = new GeneralManager();
        initComponents();
        if (data != null) {
            this.promotion = new Promotion(Integer.parseInt(data.get(0).toString()), new Position((String) data.get(1), new Department((String) data.get(2))), manager.parseDate((String) data.get(3)));
        }
        initUI();
    }

    private void initUI() {
        setLocationRelativeTo(this);
        manager.loadCombobox("SELECT name FROM department", comboDepartment);
        if (promotion != null) {
            comboPosition.setSelectedItem(promotion.getPosition().getName());
            comboDepartment.setSelectedItem(promotion.getPosition().getDepartment().getName());
//            txtDate.setText(manager.formatDate(promotion.getTime()));
            dPic.setDate(promotion.getTime());
        }
    }

    private void save() {
        String SQL;
        String positionName = comboPosition.getSelectedItem().toString();
        if (positionName == null || positionName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Position is required !");
            return;
        }
        String department = comboDepartment.getSelectedItem().toString();

        Date date = dPic.getDate();
//        if (manager.parseDate(txtDate.getText()) == null) {
//            JOptionPane.showMessageDialog(this, "Date not wellform !");
//            return;
//        }
//        date = manager.parseDate(txtDate.getText());
        Department dpm = new Department(department);
        Position pos = new Position(positionName, dpm);
        SQL="SELECT position.ID FROM position "
                + "INNER JOIN department "
                + "ON department.ID=position.department_ID "
                + "WHERE department.name='"+dpm.getName()+"' "
                + "AND position.name='"+pos.getName()+"';";
        int ID_Position=manager.getIDEdentity(SQL);
        if(ID_Position==-1){
            JOptionPane.showMessageDialog(this, "Position not found !");
            dispose();
            return;
        }
        pos.setID(ID_Position);
        if (promotion == null) {
            promotion = new Promotion(pos, date);
        } else {
            promotion.setPosition(pos);
            promotion.setTime(date);
        }
        
        SQL = "SELECT 1 FROM position "
                + "INNER JOIN department "
                + "ON position.department_ID=department.ID "
                + "INNER JOIN promotion "
                + "ON position.ID=promotion.position_ID "
                + "WHERE promotion.date='" + manager.formatDate(promotion.getTime()) + "'";
        if (!manager.checkUnique(SQL)) {
            JOptionPane.showMessageDialog(this, "Time must be unique !");
            return;
        }

        newPromotion = promotion;
        dispose();
    }

    private void reset() {
        comboPosition.removeAllItems();
        initUI();
    }

    private void cancel() {
        dispose();
    }

    public Promotion getPromotion() {
        return newPromotion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboPosition = new javax.swing.JComboBox();
        comboDepartment = new javax.swing.JComboBox();
        dPic = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        btnReset = new javax.swing.JLabel();
        btnCancle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 129, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(1, 100, 151));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Position");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 25));

        jLabel3.setBackground(new java.awt.Color(1, 100, 151));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Department");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 25));

        jLabel5.setBackground(new java.awt.Color(1, 100, 151));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Date");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, 25));

        comboPosition.setBackground(new java.awt.Color(85, 153, 187));
        comboPosition.setBorder(null);
        jPanel1.add(comboPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 250, 25));

        comboDepartment.setBackground(new java.awt.Color(85, 153, 187));
        comboDepartment.setForeground(new java.awt.Color(255, 255, 255));
        comboDepartment.setBorder(null);
        comboDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDepartmentItemStateChanged(evt);
            }
        });
        jPanel1.add(comboDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 250, 25));
        jPanel1.add(dPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 250, 25));

        jLabel11.setBackground(new java.awt.Color(0, 102, 153));
        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Buy_Upgrade_30px_1.png"))); // NOI18N
        jLabel11.setText("Poromotion Detail");
        jLabel11.setIconTextGap(14);
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 50));

        btnSave.setBackground(new java.awt.Color(51, 204, 0));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_18px.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 88, 25));

        btnReset.setBackground(new java.awt.Color(0, 102, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Reset_18px_1.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setOpaque(true);
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 88, 25));

        btnCancle.setBackground(new java.awt.Color(204, 0, 0));
        btnCancle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancle.setForeground(new java.awt.Color(255, 255, 255));
        btnCancle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        btnCancle.setText("Cancel");
        btnCancle.setOpaque(true);
        btnCancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancleMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 88, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDepartmentItemStateChanged
        if (comboDepartment.getSelectedItem() != null) {
            String SQL = "SELECT position.name "
                    + "FROM position INNER JOIN department "
                    + "ON position.department_ID=department.ID "
                    + "WHERE department.name='" + comboDepartment.getSelectedItem().toString() + "'";
            manager.loadCombobox(SQL, comboPosition);
        }
    }//GEN-LAST:event_comboDepartmentItemStateChanged

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
      save();    // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
     reset();   // TODO add your handling code here:
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnCancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancleMouseClicked
    cancel();    // TODO add your handling code here:
    }//GEN-LAST:event_btnCancleMouseClicked
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancle;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnSave;
    private javax.swing.JComboBox comboDepartment;
    private javax.swing.JComboBox comboPosition;
    private com.toedter.calendar.JDateChooser dPic;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
