package Employee;

import Controls.GeneralManager;
import TableModel.Relative;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class RelationDetail extends javax.swing.JDialog {
    private Relative relatives;
    private GeneralManager manager;
    public RelationDetail(java.awt.Frame parent, boolean modal, Relative relatives) {
        super(parent, modal);
        this.manager=new GeneralManager();
        this.relatives=relatives;
        initComponents();
        setLocationRelativeTo(this);
        initUI();
    }
    private void initUI(){
        labelID.setText(relatives.getID()+"");
        labelRelation.setText(relatives.getRelation());
        labelName.setText(relatives.getName());
        labelPhone.setText(relatives.getPhone());
        labelAddress.setText(relatives.getAddress());
        labelOccupation.setText(relatives.getOccupation());
        labelGender.setText(manager.parseGender(relatives.getGender()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelRelation = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelOccupation = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 129, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(4, 74, 121));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 88, 25));

        jLabel2.setBackground(new java.awt.Color(4, 74, 121));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Relation");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 88, 25));

        jLabel3.setBackground(new java.awt.Color(4, 74, 121));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 88, 25));

        jLabel4.setBackground(new java.awt.Color(4, 74, 121));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Phone");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 88, 25));

        jLabel5.setBackground(new java.awt.Color(4, 74, 121));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Address");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 88, 25));

        labelID.setBackground(new java.awt.Color(85, 153, 187));
        labelID.setForeground(new java.awt.Color(255, 255, 255));
        labelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID.setText("ID");
        labelID.setOpaque(true);
        jPanel1.add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 230, 25));

        labelRelation.setBackground(new java.awt.Color(85, 153, 187));
        labelRelation.setForeground(new java.awt.Color(255, 255, 255));
        labelRelation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRelation.setText("Relation");
        labelRelation.setOpaque(true);
        jPanel1.add(labelRelation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 230, 25));

        labelName.setBackground(new java.awt.Color(85, 153, 187));
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Name");
        labelName.setOpaque(true);
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, 25));

        labelPhone.setBackground(new java.awt.Color(85, 153, 187));
        labelPhone.setForeground(new java.awt.Color(255, 255, 255));
        labelPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPhone.setText("Phone");
        labelPhone.setOpaque(true);
        jPanel1.add(labelPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, 25));

        labelAddress.setBackground(new java.awt.Color(85, 153, 187));
        labelAddress.setForeground(new java.awt.Color(255, 255, 255));
        labelAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddress.setText("Address");
        labelAddress.setOpaque(true);
        jPanel1.add(labelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 230, 25));

        jLabel6.setBackground(new java.awt.Color(4, 74, 121));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Occupation");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 88, 25));

        labelOccupation.setBackground(new java.awt.Color(85, 153, 187));
        labelOccupation.setForeground(new java.awt.Color(255, 255, 255));
        labelOccupation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOccupation.setText("Occupation");
        labelOccupation.setOpaque(true);
        jPanel1.add(labelOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 230, 25));

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        jLabel7.setText("Close");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 88, 25));

        labelGender.setBackground(new java.awt.Color(85, 153, 187));
        labelGender.setForeground(new java.awt.Color(255, 255, 255));
        labelGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGender.setText("Gender");
        labelGender.setOpaque(true);
        jPanel1.add(labelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 220, 25));

        jLabel11.setBackground(new java.awt.Color(0, 68, 102));
        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Family_30px.png"))); // NOI18N
        jLabel11.setText("Family Detail");
        jLabel11.setIconTextGap(14);
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 460, 50));

        jLabel8.setBackground(new java.awt.Color(4, 74, 121));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gender");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 90, 25));

        jLabel9.setBackground(new java.awt.Color(0, 153, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Ok_18px.png"))); // NOI18N
        jLabel9.setText("Ok");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 70, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelOccupation;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelRelation;
    // End of variables declaration//GEN-END:variables
}
