/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainHome;

import Controls.Authentication;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aeon(Ankit RudrAshokJha)
 */
public class LoginForm extends javax.swing.JFrame {

    Authentication authentication;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
              
    }
int xMouse;
int yMouse;
    private void submit() {
        authentication = new Authentication();
        int res = authentication.login(txtUsrn.getText(), new String(txtPswd.getPassword()), comboRole.getSelectedIndex());
        if (res == Authentication.SUCCESS) {
//            JOptionPane.showMessageDialog(this, "Login Success !");
            Main main = new Main(authentication);
            main.setVisible(true);
            main.UserName.setText(txtUsrn.getText());
            dispose();
        } else if (res == Authentication.CONNECT_FAIL) {
            JOptionPane.showMessageDialog(this, "Connect Fail !");
        } else if (res == Authentication.NOT_AUTH) {
            JOptionPane.showMessageDialog(this, "Username or password incorrect !");
            txtPswd.setText("");
        }
    }
 public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(56, 102, 124));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(45,129,171));
 }
 public void setColor(JLabel Leb)
 {
     Leb.setBackground(new java.awt.Color(24, 161, 95));
     Leb.getColorModel();
 }
 
 public void resetColor(JLabel Leb)
 {
     Leb.setBackground(new java.awt.Color(4,74,121));
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        txtPswd = new javax.swing.JPasswordField();
        txtUsrn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox();
        mainFH = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jPanel114 = new javax.swing.JPanel();
        jLabel364 = new javax.swing.JLabel();
        jLabel365 = new javax.swing.JLabel();
        jLabel366 = new javax.swing.JLabel();
        jPanel74 = new javax.swing.JPanel();
        jLabel269 = new javax.swing.JLabel();
        jLabel270 = new javax.swing.JLabel();
        jLabel271 = new javax.swing.JLabel();
        jPanel101 = new javax.swing.JPanel();
        jLabel325 = new javax.swing.JLabel();
        jLabel326 = new javax.swing.JLabel();
        jLabel327 = new javax.swing.JLabel();
        jPanel86 = new javax.swing.JPanel();
        jLabel278 = new javax.swing.JLabel();
        jLabel279 = new javax.swing.JLabel();
        jLabel280 = new javax.swing.JLabel();
        jPanel91 = new javax.swing.JPanel();
        jLabel293 = new javax.swing.JLabel();
        jLabel294 = new javax.swing.JLabel();
        jLabel295 = new javax.swing.JLabel();
        jPanel95 = new javax.swing.JPanel();
        jLabel306 = new javax.swing.JLabel();
        jLabel307 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 102, 255));
        setLocation(new java.awt.Point(200, 100));
        setMinimumSize(new java.awt.Dimension(959, 520));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 121, 165));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(959, 629));
        jPanel1.setPreferredSize(new java.awt.Dimension(959, 629));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(4, 74, 121));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Login_18px.png"))); // NOI18N
        btnLogin.setText("LogIn");
        btnLogin.setIconTextGap(14);
        btnLogin.setOpaque(true);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Tune_24px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 30, 30));

        show.setBackground(new java.awt.Color(4, 74, 121));
        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Show_Password_22px_2.png"))); // NOI18N
        show.setToolTipText("");
        show.setEnabled(false);
        show.setOpaque(true);
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showMouseExited(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 30, 25));

        txtPswd.setBackground(new java.awt.Color(85, 153, 187));
        txtPswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPswd.setForeground(new java.awt.Color(176, 224, 230));
        txtPswd.setText("Paasword");
        txtPswd.setBorder(null);
        txtPswd.setEchoChar((char) 0);
        txtPswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPswdMouseClicked(evt);
            }
        });
        txtPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswdActionPerformed(evt);
            }
        });
        jPanel1.add(txtPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 210, 25));

        txtUsrn.setBackground(new java.awt.Color(85, 153, 187));
        txtUsrn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsrn.setForeground(new java.awt.Color(176, 224, 230));
        txtUsrn.setText(" Username");
        txtUsrn.setBorder(null);
        txtUsrn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsrnMouseClicked(evt);
            }
        });
        txtUsrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsrnActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 240, 25));

        jLabel12.setBackground(new java.awt.Color(4, 74, 121));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(176, 224, 230));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Theatre_Mask_22px.png"))); // NOI18N
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 30, 25));

        jLabel14.setBackground(new java.awt.Color(4, 74, 121));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Password_22px_3.png"))); // NOI18N
        jLabel14.setToolTipText("");
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 30, 25));

        comboRole.setBackground(new java.awt.Color(85, 153, 187));
        comboRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Admin", "Select User Role" }));
        comboRole.setSelectedItem("Select User Role");
        comboRole.setToolTipText("");
        comboRole.setBorder(null);
        jPanel1.add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 240, 25));

        mainFH.setBackground(new java.awt.Color(0, 102, 153));
        mainFH.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainFH.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        mainFH.setPreferredSize(new java.awt.Dimension(1331, 21));
        mainFH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainFHMouseDragged(evt);
            }
        });
        mainFH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainFHMousePressed(evt);
            }
        });
        mainFH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainFHKeyPressed(evt);
            }
        });
        mainFH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 51, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_18px_3.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        mainFH.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 20, 20));

        jLabel13.setBackground(new java.awt.Color(51, 204, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_18px_3.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        mainFH.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 20, 20));

        jLabel6.setBackground(new java.awt.Color(85, 153, 187));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Infinity_32px.png"))); // NOI18N
        jLabel6.setText("AEON  School  Management  System");
        jLabel6.setIconTextGap(14);
        jLabel6.setOpaque(true);
        mainFH.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 580, 30));

        jLabel15.setBackground(new java.awt.Color(4, 74, 121));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(176, 224, 230));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Login_32px.png"))); // NOI18N
        jLabel15.setText("LogIn");
        jLabel15.setOpaque(true);
        mainFH.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 390, 30));

        jPanel1.add(mainFH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));

        jSeparator4.setBackground(new java.awt.Color(85, 153, 187));
        jSeparator4.setForeground(new java.awt.Color(85, 153, 187));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 10, 490));

        jLabel16.setBackground(new java.awt.Color(4, 74, 121));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_22px_1.png"))); // NOI18N
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 30, 25));

        jPanel114.setBackground(new java.awt.Color(45, 129, 171));
        jPanel114.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel114MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel114MouseExited(evt);
            }
        });

        jLabel364.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_Account_38px.png"))); // NOI18N

        jLabel365.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel365.setForeground(new java.awt.Color(255, 255, 255));
        jLabel365.setText("Users");

        jLabel366.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel366.setForeground(new java.awt.Color(255, 255, 255));
        jLabel366.setText(" Management");

        javax.swing.GroupLayout jPanel114Layout = new javax.swing.GroupLayout(jPanel114);
        jPanel114.setLayout(jPanel114Layout);
        jPanel114Layout.setHorizontalGroup(
            jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel114Layout.createSequentialGroup()
                .addGroup(jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel114Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel366))
                    .addGroup(jPanel114Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel365, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel364))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel114Layout.setVerticalGroup(
            jPanel114Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel114Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel364)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel365)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel366)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 120, 120));

        jPanel74.setBackground(new java.awt.Color(45, 129, 171));
        jPanel74.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel74MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel74MouseMoved(evt);
            }
        });
        jPanel74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel74MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel74MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel74MouseExited(evt);
            }
        });

        jLabel269.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Student_Male_38px.png"))); // NOI18N

        jLabel270.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel270.setForeground(new java.awt.Color(255, 255, 255));
        jLabel270.setText("Student ");

        jLabel271.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel271.setForeground(new java.awt.Color(255, 255, 255));
        jLabel271.setText("Infomation");

        javax.swing.GroupLayout jPanel74Layout = new javax.swing.GroupLayout(jPanel74);
        jPanel74.setLayout(jPanel74Layout);
        jPanel74Layout.setHorizontalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel74Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel74Layout.createSequentialGroup()
                        .addGroup(jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel270, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel74Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel269)))
                        .addGap(17, 17, 17))
                    .addComponent(jLabel271, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel74Layout.setVerticalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel74Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel269)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel270)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel271)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, 120));

        jPanel101.setBackground(new java.awt.Color(45, 129, 171));
        jPanel101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel101MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel101MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel101MouseExited(evt);
            }
        });

        jLabel325.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Class_38px.png"))); // NOI18N

        jLabel326.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel326.setForeground(new java.awt.Color(255, 255, 255));
        jLabel326.setText("Extra ");

        jLabel327.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel327.setForeground(new java.awt.Color(255, 255, 255));
        jLabel327.setText("Curricular");

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel101Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel327)
                    .addGroup(jPanel101Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel325)
                            .addComponent(jLabel326))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel101Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel325)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel326)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel327)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, 120));

        jPanel86.setBackground(new java.awt.Color(45, 129, 171));
        jPanel86.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel86MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel86MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel86MouseExited(evt);
            }
        });

        jLabel278.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Graduation_Cap_38px.png"))); // NOI18N

        jLabel279.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel279.setForeground(new java.awt.Color(255, 255, 255));
        jLabel279.setText("Marks");

        jLabel280.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel280.setForeground(new java.awt.Color(255, 255, 255));
        jLabel280.setText(" Management");

        javax.swing.GroupLayout jPanel86Layout = new javax.swing.GroupLayout(jPanel86);
        jPanel86.setLayout(jPanel86Layout);
        jPanel86Layout.setHorizontalGroup(
            jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel86Layout.createSequentialGroup()
                .addGroup(jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel86Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel278))
                    .addGroup(jPanel86Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel86Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel279))
                            .addComponent(jLabel280))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel86Layout.setVerticalGroup(
            jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel86Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel278)
                .addGap(18, 18, 18)
                .addComponent(jLabel279)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel280)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 120, 120));

        jPanel91.setBackground(new java.awt.Color(45, 129, 171));
        jPanel91.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel91MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel91MouseMoved(evt);
            }
        });
        jPanel91.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel91MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel91MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel91MouseExited(evt);
            }
        });

        jLabel293.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Profile_38px.png"))); // NOI18N

        jLabel294.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel294.setForeground(new java.awt.Color(255, 255, 255));
        jLabel294.setText("Employees");

        jLabel295.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel295.setForeground(new java.awt.Color(255, 255, 255));
        jLabel295.setText("Infomation");

        javax.swing.GroupLayout jPanel91Layout = new javax.swing.GroupLayout(jPanel91);
        jPanel91.setLayout(jPanel91Layout);
        jPanel91Layout.setHorizontalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel91Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel91Layout.createSequentialGroup()
                        .addComponent(jLabel293)
                        .addGap(24, 24, 24))
                    .addComponent(jLabel295, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel294, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel91Layout.setVerticalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel91Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel293)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel294)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel295)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, 120));

        jPanel95.setBackground(new java.awt.Color(45, 129, 171));
        jPanel95.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel95MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel95MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel95MouseExited(evt);
            }
        });

        jLabel306.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Department_38px.png"))); // NOI18N

        jLabel307.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel307.setForeground(new java.awt.Color(255, 255, 255));
        jLabel307.setText("Departments");

        javax.swing.GroupLayout jPanel95Layout = new javax.swing.GroupLayout(jPanel95);
        jPanel95.setLayout(jPanel95Layout);
        jPanel95Layout.setHorizontalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel95Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel95Layout.createSequentialGroup()
                        .addComponent(jLabel306)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel95Layout.createSequentialGroup()
                        .addComponent(jLabel307)
                        .addGap(16, 16, 16))))
        );
        jPanel95Layout.setVerticalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel95Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel306)
                .addGap(18, 18, 18)
                .addComponent(jLabel307)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 120, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 959, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
 new SettingsGUI(this, true).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void mainFHMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFHMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);// TODO add your handling code here:
    }//GEN-LAST:event_mainFHMouseDragged

    private void mainFHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFHMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_mainFHMousePressed

    private void mainFHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainFHKeyPressed

    }//GEN-LAST:event_mainFHKeyPressed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        txtPswd.setEchoChar((char) 0);        // TODO add your handling code here:
    }//GEN-LAST:event_showMouseClicked

    private void showMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseExited
        txtPswd.setEchoChar('.');     // TODO add your handling code here:
    }//GEN-LAST:event_showMouseExited

    private void txtPswdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPswdMouseClicked
        txtPswd.setEchoChar('.');
        txtPswd.setText(null);
        show.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswdMouseClicked

    private void txtUsrnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsrnMouseClicked
        txtUsrn.setText(null);  // TODO add your handling code here:
    }//GEN-LAST:event_txtUsrnMouseClicked

    private void txtUsrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsrnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsrnActionPerformed

    private void txtPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswdActionPerformed
submit();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswdActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
     this.setState(LoginForm.ICONIFIED);    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
      submit();
      // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
     xMouse=evt.getX();
        yMouse=evt.getY();    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
 int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel74MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel74MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel74MouseDragged

    private void jPanel74MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel74MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel74MouseMoved

    private void jPanel74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel74MouseClicked
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel74MouseClicked

    private void jPanel74MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel74MouseExited
 resetColor(jPanel74);         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel74MouseExited

    private void jPanel101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel101MouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel101MouseClicked

    private void jPanel86MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel86MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_jPanel86MouseClicked

    private void jPanel91MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel91MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel91MouseDragged

    private void jPanel91MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel91MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel91MouseMoved

    private void jPanel91MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel91MouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_jPanel91MouseClicked

    private void jPanel91MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel91MouseExited
 resetColor(jPanel91);         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel91MouseExited

    private void jPanel95MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel95MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel95MouseClicked

    private void jPanel114MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel114MouseEntered
 setColor(jPanel114);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel114MouseEntered

    private void jPanel74MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel74MouseEntered
  setColor(jPanel74);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel74MouseEntered

    private void jPanel91MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel91MouseEntered
 setColor(jPanel91);         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel91MouseEntered

    private void jPanel101MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel101MouseEntered
 setColor(jPanel101);         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel101MouseEntered

    private void jPanel86MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel86MouseEntered
 setColor(jPanel86);         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel86MouseEntered

    private void jPanel95MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel95MouseEntered
  setColor(jPanel95);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel95MouseEntered

    private void jPanel114MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel114MouseExited
 resetColor(jPanel114);       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel114MouseExited

    private void jPanel101MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel101MouseExited
  resetColor(jPanel101);       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel101MouseExited

    private void jPanel86MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel86MouseExited
 resetColor(jPanel86);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel86MouseExited

    private void jPanel95MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel95MouseExited
  resetColor(jPanel95);       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel95MouseExited

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
  setColor(btnLogin);      // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
resetColor(btnLogin);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set thes look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is notw available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>
   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
   });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogin;
    private javax.swing.JComboBox comboRole;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel271;
    private javax.swing.JLabel jLabel278;
    private javax.swing.JLabel jLabel279;
    private javax.swing.JLabel jLabel280;
    private javax.swing.JLabel jLabel293;
    private javax.swing.JLabel jLabel294;
    private javax.swing.JLabel jLabel295;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel325;
    private javax.swing.JLabel jLabel326;
    private javax.swing.JLabel jLabel327;
    private javax.swing.JLabel jLabel364;
    private javax.swing.JLabel jLabel365;
    private javax.swing.JLabel jLabel366;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel114;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel86;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel mainFH;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField txtPswd;
    private javax.swing.JTextField txtUsrn;
    // End of variables declaration//GEN-END:variables
}
